version: '3.7'

services:
  db-test:
    image: postgres:latest
    container_name: db-test
    env_file: .env.test
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - api-test-network
  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-test
    container_name: api-test
    env_file: .env.test
    environment:
      - NODE_ENV=test
      - API_PORT=$API_PORT
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - api-test-network
    depends_on:
      - db-test
    command: ./docker/wait-for.sh db-test:$DB_PORT -- npm run test
networks:
  api-test-network:
    driver: bridge